Basic examples corrections
With the basic examples verbatim, the server was throwing the following error

```
.../sandbox/node_modules/node-ipc/lib/socketServer.js:34
    socket.write(
           ^
TypeError: undefined is not a function
...
```

Adding the missing `socket` reference on line 536 corrected this problem.

There was also an error in the `require` statement.